### ISSUE TITLE
Base ROCm images are inaccessible! This defeats the purpose of this repository!

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [amd/InfinityHub-CI#11]
Base ROCm images are inaccessible! This defeats the purpose of this repository!:

```
$ docker login
Login Succeeded

$ docker pull rocm_gpu:5.7
Error response from daemon: pull access denied for rocm_gpu, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

$ docker pull rocm_gpu:6.1.1
Error response from daemon: pull access denied for rocm_gpu, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Obviously, without access, none of the provided Dockerfiles can be used to build images of the tools in this repository, like OpenFOAM, nekRS, etc. Are you planning to make this base images available? Or what is the plan for the community use of your repository?

Regards,
Alexis

**Comment by AlexisEspinosaGayosso** [comment]
Now I see that we are supposed to build those images ourselves using the recipe in `base-gpu-mpi-rocm-docker`. Right?

But that is not possible! Your recipes are throwing an error! I will raise a separate issue for that!

And you can close this one. (I guess the only improvement related to this issue would be to make it more clear to the public that the first step to build your containers is indeed to build the base image (rocm_gpu) needed by each of the tools. (Well, when the recipe for the base image works. I hope you can fix that soon!)

**Comment by cmcknigh** [comment]
Yes, as noted in the readme file, you should build the base image based on the version of rocm you wish to install. 

The recipe for the base image has been updated, a path variable was incorrect. 
Sorry for the inconvenience.
