### ISSUE TITLE
Default image pulls unavaliable 

### ISSUE THREAD

**Issue by riony** [amd/InfinityHub-CI#15]
running 

docker build -t mycontainer/openfoam -f /path/to/Dockerfile . 

unable to locate suitable docker image from repos

Changing 

ARG IMAGE="rocm_gpu:5.7"

to a up to date image fixes issue.

**Comment by cmcknigh** [comment]
Please find the instructions on how to build your own base container here:
https://github.com/amd/InfinityHub-CI/tree/main/base-gpu-mpi-rocm-docker

However, I have found that there are issues with the openfoam container, I am currently trying to understand the problem and resolve it.
