### ISSUE TITLE
relion update for MI300x

### ISSUE THREAD

**Issue by romxero** [amd/InfinityHub-CI#16]
Hi there, 

When trying to use the container on the MI300x hardware we ran into issues of the software running. 

We were wondering if this port could be updated for the MI300x? 
If it requires more effort than a simple recompile, then what would be needed for this software to be fully ported to the AMD hardware? 

Thx. 

-RC

**Comment by cmcknigh** [comment]
Relion uses textures that are not currently supported on the GFX942 architecture, used by MI300X and MI300A.

When the required textures are supported, a recipe will be created and added to this repository for Relion.
