### ISSUE TITLE
Is --save-temps option required for building GROMACS?

### ISSUE THREAD

**Issue by araghave7** [amd/InfinityHub-CI#5]
https://github.com/amd/InfinityHub-CI/blob/693e75b8ec6846e89c076d4e3d930aa2246acc56/gromacs-docker/Dockerfile#LL120C8-L120C89

**Comment by jdmaia** [comment]
No. You can get rid of it.

**Comment by cmcknigh** [comment]
Update has been made. --save-temps has been removed in the updated recipe.
