### ISSUE TITLE
Updating TensorFlow and PyTorch containers

### ISSUE THREAD

**Issue by dipietrantonio** [amd/InfinityHub-CI#6]
Hi All, I have noticed that new TensorFlow + rocm containers are being published here https://hub.docker.com/r/rocm/tensorflow/tags instead of https://hub.docker.com/r/amdih/tensorflow . In addition, the containers published in amdih for Tensorflow and PyTorch are quite old, with PyTorch not being published under `rocm` like TensorFlow.

When can we expect a newer PyTorch container? And what is the default Docker Repo we should follow?

Thanks

**Comment by dipietrantonio** [comment]
Hi @dabolding, any news?

**Comment by dabolding** [comment]
Apologies for the delay. I believe these containers have been updated
